### ISSUE TITLE
Z_normalise gives no error when acting on an empty column

### ISSUE THREAD

**Issue by ThomasReyEY** [krystofmincevey/eyft#2]
Z_Normalise returns Nan's  when acting on an empty column, not necessary a problem but it is cleaner if we catch this error in stead of proceeding with Nan's as it gets more and more difficult to localise the issue. 

Problem is located at stdev = 0 and then dividing by stdev. 

Arthur I would suggest to ad an if lstatement like : 
if stdev != 0: 
    column = column/stdev

**Comment by ARED2000** [comment]
added test past
