### ISSUE TITLE
Z_Normalise stdev gives unexpected results 

### ISSUE THREAD

**Issue by ThomasReyEY** [krystofmincevey/eyft#3]
Z_normalise gives unexpected result for std 

for example on the array:
[1, 1, 1, 1, -1, -1, -1, -1]

I get a std of 0,94..., while I would expect a std of 1. 

Issue seems to lie in the parameter ddof (delta degrees of freedom): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html
standard set to 1

Do we know why this is the standard, do we just put ddof to 0? 

Arthur this is then simply:
df[col].std(ddof=0) (if we want this behaviour)

**Comment by ARED2000** [comment]
fixed
