### ISSUE TITLE
min_max_scale

### ISSUE THREAD

**Issue by ThomasReyEY** [krystofmincevey/eyft#4]
Min_Max_Scale gives Nan's when the input column is uniform 

for example: 1,1,1,1 gives nan

Arthur, maybe implement a check to see if the min and max value are equal? 

I think best practise is to leave the column as is, but raise a warning to the user so we know that the function observed some weird behaviour? 

Here is the warning package: 
https://docs.python.org/3/library/warnings.html#module-warnings

**Comment by ARED2000** [comment]
I think the problem here was if max - min = 0 the calculation gives an error
So what I did now was adding an if statement as follows: if max - min != 0: df[col] .....

The test has passed now !
